Feature 3 get workouts
dennymin/final-project pull request #15
Opened 2021-09-13 22:49 UTC by dennymin

![final project feature 3 get workouts](https://user-images.githubusercontent.com/85311223/133166947-4b6460be-2c0c-44ab-b394-4312f9b8e2b2.gif)

2021-09-13 22:57 UTC, thebearingedge requested changes
Ok it's coming along nicely. Please see my comments. Also, your user shouldn't have to click twice to see the menu items. Just show the menu items when the drawer is opened.

2021-09-13 22:57 UTC, thebearingedge commented on client/components/temp-drawer.jsx
> +  };
How about `isDrawerOpen` and `setIsDrawerOpen` instead of just `state` and `setState`

2021-09-13 22:57 UTC, thebearingedge commented on client/components/temp-drawer.jsx
> +  const list = () => {
Does this need to be in a function or can you just cut-paste these React elements into your return?

2021-09-13 22:57 UTC, thebearingedge commented on client/pages/your-workouts.jsx
> +            <ThemeProvider theme ={theme}>
We don't really do theming like this. The Theme should only be defined in one place and wrap the whole app. Unless this is required by some library you are using?

2021-09-13 22:57 UTC, thebearingedge commented on package.json
> +    "clsx": "^1.1.1",
Can you remove this clsx thing?

2021-09-14 00:58 UTC, dennymin commented
![final project feature 3 get workouts correction](https://user-images.githubusercontent.com/85311223/133176526-89437d2a-5648-4c4a-8a95-c8f785552d20.gif)

2021-09-14 02:09 UTC, thebearingedge approved these changes

2021-09-14 05:18 UTC, merged