Feature 5 fitness report
dennymin/final-project pull request #17
Opened 2021-09-15 21:39 UTC by dennymin

![final project feature 5 fitness report](https://user-images.githubusercontent.com/85311223/133513269-ddf3d480-2ed2-40e1-8e83-19270649272b.gif)

2021-09-15 21:52 UTC, thebearingedge requested changes

2021-09-15 21:52 UTC, thebearingedge commented on server/index.js
> +  and    DATE("workouts"."date") <= '${endDate}'
We never put untrusted data into our SQL. Use a parameterized query instead.

2021-09-15 21:52 UTC, thebearingedge commented on client/pages/your-workouts.jsx
> +      const workingDate = workoutDate.toGMTString().slice(0, 16);
I recommend using the `date-fns` library for all of your date formatting.

2021-09-15 21:52 UTC, thebearingedge commented on client/pages/home.jsx
> +  }
This is _a lot_ of logic to be re-run every time the component renders. Instead, format the data on the server into the correct shape before sending it to the client.

2021-09-15 21:52 UTC, thebearingedge commented on client/pages/home.jsx
> +      }, [null, startDate, endDate]);
I think you mean to put this array on line 73.

2021-09-15 21:52 UTC, thebearingedge commented on client/pages/home.jsx
> +  const defaultStartPicker = `${defaultStartYear}-${defaultStartMonth}-${defaultStartDay}`;
I recommend `date-fns` for all of your date math/formatting.

2021-09-15 21:52 UTC, thebearingedge commented on client/app.jsx
> +    }
It would probably make more sense if each page just had a header in it with a hard-coded title.

2021-09-16 00:35 UTC, dennymin commented
![final project feature 5 fitness report correction](https://user-images.githubusercontent.com/85311223/133530690-9debbac3-afd9-4c2b-902a-0040dbfaf947.gif)

2021-09-16 00:53 UTC, thebearingedge approved these changes

2021-09-16 00:56 UTC, merged